services:
  - type: web
    name: sneakerhunter
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --timeout 90 --workers 1
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.1
    autoDeploy: true